### ISSUE TITLE
Regarding the corrections

### ISSUE THREAD

**Issue by SrijaniUH** [KonstantinosF/Classification-of-Hyperspectral-Image#7]
Firstly, thanks for this amazing code. It is very nice and I learned a lot from this. However, I saw your datasets are corrected. Can you please tell me how did you do the corrections and please give me the link of the code you are using? TIA

**Comment by KonstantinosF** [comment]
Hi
I am not sure about what you mean. Can you be more specific?

What kind of corrections are you talking about?

**Comment by SrijaniUH** [comment]
I mean corrections for Sun angle, atmospheric effects etc

**Comment by KonstantinosF** [comment]
I didn't apply any atmospheric correction nor any geo-reference. The dataset includes reflectance values.

More informations about the indian pines dataset can be found from Purdue University (provider) at the following link:
[https://purr.purdue.edu/publications/1947/1](url)

I hope that helps.
Thank you for your message

**Comment by SrijaniUH** [comment]
I saw the datasets include reflectance values, but aren't there some atmospheric or solar effects on them? I will read the paper. Thanks a lot!

**Comment by SrijaniUH** [comment]
BTW the link you gave didn't open. Could you kindly check?

**Comment by KonstantinosF** [comment]
> I saw the datasets include reflectance values, but aren't there some atmospheric or solar effects on them? I will read the paper. Thanks a lot!

I suppose these corrections have already been applied. At least that's what I assumed when I was building the project.

> BTW the link you gave didn't open. Could you kindly check?

Try this 
http://www.ehu.eus/ccwintco/index.php/Hyperspectral_Remote_Sensing_Scenes#Indian_Pines

**Comment by SrijaniUH** [comment]
Oh okay! Sounds good! actually I am collecting my own data! And so was looking for something like that!
Thanks anyways! Thanks again for the amazing codebase!
